=== iStandaarden/iWlz-codelijsten-APiWlz/schema/codelijst.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2020 sp1 (http://www.altova.com) by  (Zorginstituut Nederland) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" elementFormDefault="qualified" attributeFormDefault="unqualified" vc:minVersion="1.1">
	<xs:element name="Codelijst">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="CodelijstId" type="xs:string"/>
				<xs:element name="Codelijstnaam" type="xs:string"/>
				<xs:element name="Codelijstomschrijving" type="xs:string"/>
				<xs:element name="Codelijstverwijzing" type="xs:string" minOccurs="0"/>
				<xs:element name="Codewaarden">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Codewaarde" type="Codewaarde" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Codewaarde">
		<xs:sequence>
			<xs:element name="id" type="xs:string"/>
			<xs:element name="omschrijving" type="xs:string"/>
			<xs:element name="ingangsdatum" type="xs:date"/>
			<xs:element name="experiratiedatum" type="xs:date" minOccurs="0"/>
			<xs:element name="mutatiedatum" type="xs:date" minOccurs="0"/>
			<xs:element name="mutatie" type="mutatie" minOccurs="0"/>
			<xs:element name="type" type="xs:string" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="mutatie">
		<xs:restriction base="xs:string">
			<xs:enumeration value="gewijzigd"/>
			<xs:enumeration value="vervallen"/>
			<xs:enumeration value="toegevoegd"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== iStandaarden/iWlz-codelijsten-APiWlz/codelijsten/COD046/COD046.xml
<?xml version="1.0" encoding="UTF-8"?>
<Codelijst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="codelijst.xsd">
    <CodelijstId>COD046</CodelijstId>
    <Codelijstnaam>COD046: Geslacht</Codelijstnaam>
    <Codelijstomschrijving>Unieke aanduiding van de sexe van een persoon.</Codelijstomschrijving>
    <Codelijstverwijzing>uri</Codelijstverwijzing>
    <Codewaarden>
        <Codewaarde>
            <id>0</id>
            <omschrijving>Onbekend</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>1</id>
            <omschrijving>Mannelijk</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>2</id>
            <omschrijving>Vrouwelijk</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
    </Codewaarden>
</Codelijst>

=== iStandaarden/iWlz-codelijsten-APiWlz/codelijsten/COD999/COD999.xml
<?xml version="1.0" encoding="UTF-8"?>
<Codelijst xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="codelijst.xsd">
    <CodelijstId>COD999</CodelijstId>
    <Codelijstnaam>COD999: Voorkeur client</Codelijstnaam>
    <Codelijstomschrijving>Gecodeerde aanduiding van de voorkeur van de client ten aanzien van plaats en/of vorm van zorglevering.</Codelijstomschrijving>
    <Codelijstverwijzing>uri</Codelijstverwijzing>
    <Codewaarden>
        <Codewaarde>
            <id>1</id>
            <omschrijving>Functie in natura</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
            <experiratiedatum>2018-04-01</experiratiedatum>
            <mutatiedatum>2017-07-01</mutatiedatum>
            <mutatie>vervallen</mutatie>
        </Codewaarde>
        <Codewaarde>
            <id>2</id>
            <omschrijving>Persoonsgebonden budget (PGB)</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>3</id>
            <omschrijving>Zorg thuis (niet nader gespecificeerd)</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>4</id>
            <omschrijving>Verblijf</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
            <mutatiedatum>2017-07-01</mutatiedatum>
            <mutatie>gewijzigd</mutatie>
        </Codewaarde>
        <Codewaarde>
            <id>5</id>
            <omschrijving>Volledig pakket thuis (VPT)</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>6</id>
            <omschrijving>Combinatie PGB/MPT</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>7</id>
            <omschrijving>Modulair pakket thuis (MPT)</omschrijving>
            <ingangsdatum>2015-01-01</ingangsdatum>
        </Codewaarde>
        <Codewaarde>
            <id>8</id>
            <omschrijving>combinatie VPT/PGB</omschrijving>
            <ingangsdatum>2020-01-01</ingangsdatum>
            <mutatiedatum>2019-06-01</mutatiedatum>
            <mutatie>toegevoegd</mutatie>
        </Codewaarde>
        <Codewaarde>
            <id>9</id>
            <omschrijving>combinatie Verblijf/PGB</omschrijving>
            <ingangsdatum>2020-01-01</ingangsdatum>
            <mutatiedatum>2019-06-01</mutatiedatum>
            <mutatie>toegevoegd</mutatie>
        </Codewaarde>
        <Codewaarde>
            <id>10</id>
            <omschrijving>Deeltijdverblijf (DTV)</omschrijving>
            <ingangsdatum>2021-01-01</ingangsdatum>
            <mutatiedatum>2020-06-01</mutatiedatum>
            <mutatie>toegevoegd</mutatie>
        </Codewaarde>
    </Codewaarden>
</Codelijst>
